"""
    settings for VNEGMAS project

    Generated by `Yue Ning`

    For more information see,
    ``   
"""

DEFAULT_CHARTS = [
    
]

# ALL DEFAULT DATA FROM NEGMAS THAT CAN BE SHOWN in NEGMAS, BASE ON SIMULATION STEP
"""
    '_balance_bank', 
    '_balance_insurance', 
    '_balance_society', 
    '_market_size_total', 
    '_storage_insurance', 
    'activity_level', 
    'balance_c',
    'balance_factories ',
    'balance_m', 
    'breach_level', 
    'market_size', 
    'n_bankrupt', 
    'n_breaches', 
    'n_cfps', 
    'n_cfps_on_board_after',
    'n_cfps_on_board_before', 
    'n_contracts_cancelled', 
    'n_contracts_concluded', 
    'n_contracts_executed',
    'n_contracts_nullified', 
    'n_contracts_signed', 
    'n_negotiation_rounds_failed', 
    'n_negotiation_rounds_successful', 
    'n_negotiations', 
    'n_registered_negotiations_after', 
    'n_registered_negotiations_before', 
    'production_failures', 
    'storage_c', 
    'storage_factories', 
    'storage_m',
"""

OFFLINE_DEFAULT_CHARTS = [
    '_balance_bank', 
    '_balance_insurance',
    '_balance_society',
    '_market_size_total', 
    'activity_level',
    'n_contracts_signed',
    'breach_level',
]

# EXTERNE CHARTS THAT USE NegmasDataBridge AND  DataVNegmasBridge TO REGISTER
EXTERNE_CHARTS = [

]

# ALL MONITOR MODES
# OnlineSerial,  OnlineFile, OnlineMemory, Offline
MONITOR_MODES = 'OnlineSerial'