"""
    settings for VNEGMAS project

    Generated by `Yue Ning` 2.8.2019

    For more information see,
    ``   
"""

# ALL PARAMETER USED FOR REAL TIME
"""
world 20190803-170645k1Gj_a2b8-a2b8.00002.00001, 
    the stats are defaultdict(<class 'list'>,
    'n_cfps_on_board_before', 
    'n_registered_negotiations_before'
    'n_contracts_executed'
    'n_contracts_cancelled'
    'n_breaches'
    'breach_level'
    'n_contracts_signed'
    'n_contracts_concluded'
    'n_negotiations'
    'n_negotiation_rounds_successful'
    'n_negotiation_rounds_failed'
    'n_registered_negotiations_after'
    'activity_level'
    'n_cfps'
    'n_cfps_on_board_after'
    'n_contracts_nullified'
    'n_bankrupt'
    '_balance_bank'
    '_balance_society'
    '_balance_insurance'
    '_storage_insurance'
    'balance_m_0'
    'storage_m_0'
    'balance_m_1'
    'storage_m_1'
    'balance_m_2'
    'storage_m_2'
    'balance_m_3'
    'storage_m_3'
    'balance_m_4'
    'storage_m_4'
    balance_c_0'
    'storage_c_0'
    'balance_c_1'
    'storage_c_1'
    'balance_c_2'
    'storage_c_2'
    'balance_c_3'
    'storage_c_3
    'balance_c_4'
    'storage_c_4
    'balance_greedy@1_0'
    'storage_greedy@1_0'
    'balance_greedy@1_1'
    'storage_greedy@1_1'
    'balance_greedy@1_2'
    'storage_greedy@1_2': [0, 0, 0], 'balance__df_1_3': [1000.0, 1000.0, 1000.0], 'storage__df_1_3': [0, 0, 0], 'balance__df_1_4': [1000.0, 1000.0, 1000.0], 'storage__df_1_4': [0, 0, 0], 'balance_greedy@2_0': [1000.0, 1000.0, 1000.0], 'storage_greedy@2_0': [0, 0, 0], 'balance_greedy@2_1': [1000.0, 1000.0, 1000.0], 'storage_greedy@2_1': [0, 0, 0], 'balance_greedy@2_2': [1000.0, 1000.0, 1000.0], 'storage_greedy@2_2': [0, 0, 0], 'balance_greedy@2_3': [1000.0, 1000.0, 1000.0], 'storage_greedy@2_3': [0, 0, 0], 'balance_greedy@2_4': [1000.0, 1000.0, 1000.0], 'storage_greedy@2_4': [0, 0, 0], 'balance_greedy@2_5': [1000.0, 1000.0, 1000.0], 'storage_greedy@2_5': [0, 0, 0], 'balance_greedy@2_6': [1000.0, 1000.0, 1000.0], 'storage_greedy@2_6': [0, 0, 0], 'balance__df_2_7': [1000.0, 1000.0, 1000.0], 'storage__df_2_7': [0, 0, 0], 'balance_greedy@3_0': [1000.0, 1000.0, 1000.0], 'storage_greedy@3_0': [0, 0, 0], 'balance_greedy@3_1': [1000.0, 1000.0, 1000.0], 'storage_greedy@3_1': [0, 0, 0], 'balance__df_3_2': [1000.0, 1000.0, 1000.0], 'storage__df_3_2': [0, 0, 0], 
    'balance__df_3_3': [1000.0, 1000.0, 1000.0], 'storage__df_3_3': [0, 0, 0], 'balance__df_3_4': [1000.0, 1000.0, 1000.0], 'storage__df_3_4': [0, 0, 0], 
    'balance_greedy@4_0': [1000.0, 1000.0, 1000.0], 'storage_greedy@4_0': [0, 0, 0], 
    'balance_greedy@4_1': [1000.0, 1000.0, 1000.0], 'storage_greedy@4_1': [0, 0, 0], 
    'balance_greedy@4_2': [1000.0, 1000.0, 1000.0], 'storage_greedy@4_2': [0, 0, 0], 
    'balance_greedy@4_3': [1000.0, 1000.0, 1000.0], 'storage_greedy@4_3': [0, 0, 0], 
    'balance__df_4_4': [1000.0, 1000.0, 1000.0], 'storage__df_4_4': [0, 0, 0],
    'balance_greedy@5_0': [1000.0, 1000.0, 999.31], 'storage_greedy@5_0': [0, 0, 0], 
    'balance_greedy@5_1': [1000.0, 1000.0, 999.0999999999999], 'storage_greedy@5_1': [0, 0, 0], 
    'balance_greedy@5_2': [1000.0, 1000.0, 999.4449999999999], 'storage_greedy@5_2': [0, 0, 0], 
    'balance_greedy@5_3': [1000.0, 1000.0, 998.56], 'storage_greedy@5_3': [0, 0, 0],
    'balance__df_5_4': [1000.0, 1000.0, 1000.0], 'storage__df_5_4': [0, 0, 0], 
    'balance__df_5_5': [1000.0, 1000.0, 1000.0], 'storage__df_5_5': [0, 0, 0], 
    'balance__df_5_6': [1000.0, 1000.0, 999.3399999999999],'storage__df_5_6': [0, 0, 0], 
    'balance__df_5_7': [1000.0, 1000.0, 1000.0], 'storage__df_5_7': [0, 0, 0],
    'market_size': [31000.0, 31000.0, 30995.755], 
    'production_failures': [0.0, 0.0, 0.0],
    '_market_size_total': [31000.0, 31000.0, 31000.0]})

"""

DEFAULT_CHARTS = [
    'n_cfps_on_board_before',
    'n_registered_negotiations_before',
    'n_contracts_executed',  
    'n_contracts_cancelled',
    'n_breaches',
    'breach_level',
    'n_contracts_signed',
    'n_contracts_concluded',
    'n_negotiations',
    'n_negotiation_rounds_successful',
    'n_negotiation_rounds_failed',
    'n_registered_negotiations_after',
    'activity_level',
    'n_cfps',
    'n_cfps_on_board_after',
    'n_contracts_nullified',
    'n_bankrupt',
    '_balance_bank',
    '_balance_society',
]

# ALL DEFAULT DATA FROM NEGMAS THAT CAN BE SHOWN in NEGMAS, BASE ON SIMULATION STEP
"""
    '_balance_bank', 
    '_balance_insurance', 
    '_balance_society', 
    '_market_size_total', 
    '_storage_insurance', 
    'activity_level', 
    'balance_c',
    'balance_factories ',
    'balance_m', 
    'breach_level', 
    'market_size', 
    'n_bankrupt', 
    'n_breaches', 
    'n_cfps', 
    'n_cfps_on_board_after',
    'n_cfps_on_board_before', 
    'n_contracts_cancelled', 
    'n_contracts_concluded', 
    'n_contracts_executed',
    'n_contracts_nullified', 
    'n_contracts_signed', 
    'n_negotiation_rounds_failed', 
    'n_negotiation_rounds_successful', 
    'n_negotiations', 
    'n_registered_negotiations_after', 
    'n_registered_negotiations_before', 
    'production_failures', 
    'storage_c', 
    'storage_factories', 
    'storage_m',
"""

OFFLINE_DEFAULT_CHARTS = [
    '_balance_bank', 
    '_balance_insurance',
    '_balance_society',
    '_market_size_total', 
    'activity_level',
    'n_contracts_signed',
    'breach_level',
]

OFFLINE_DEFAULT_SHOWN_CHARTS = [
    '_balance_bank', 
    '_balance_insurance',
    '_balance_society',
    '_market_size_total', 
    'activity_level',
    'n_contracts_signed',
    'breach_level',
]

# EXTERNE CHARTS THAT USE NegmasDataBridge AND  DataVNegmasBridge TO REGISTER
EXTERNE_CHARTS = [

]

# ALL MONITOR MODES
# OnlineSerial,  OnlineFile, OnlineMemory, Offline
MONITOR_MODES = 'OnlineSerial'